crop videos

diff --git a/autoIeltsVideo/batch b/autoIeltsVideo/batch
--- a/autoIeltsVideo/batch
+++ b/autoIeltsVideo/batch
@@ -2,16 +2,85 @@
 
 # for each .mp3 file in audio/tts directory, start a new process with ./run.sh
 
-for f in audio/tts/*.mp3; do
-    CMD="./run.sh fake video/smale.mp4 $f"
-    echo "$(date) $CMD" >> run.log
-    eval $CMD
-    # check the result and log result to file run.log
-    if [ $? -eq 0 ]; then
-        echo "$(date) Success" >> run.log
-    else
-        echo "$(date) Failed" >> run.log
-        exit 1
+function fake() {
+  for f in audio/tts/*.mp3; do
+      CMD="./run.sh fake video/smale.mp4 $f"
+      echo "$(date) $CMD" >> run.log
+      eval $CMD
+      # check the result and log result to file run.log
+      if [ $? -eq 0 ]; then
+          echo "$(date) Success" >> run.log
+      else
+          echo "$(date) Failed" >> run.log
+          exit 1
+      fi
+
+  done
+}
+
+function cropFinalVideo() {
+  # $1: 带app屏视频文件
+  # $2: 抠对话窗
+  vWithApp=$1
+  vDialog=$2
+  #判断vDialog是否存在
+  if [ -f $vDialog ]; then
+    echo "$vDialog already exists"
+    return 0
+  fi
+  #获取vWithApp分辨率
+  vWithAppWidth=$(ffprobe -v error -select_streams v:0 -show_entries stream=width -of csv=s=x:p=0 $vWithApp)
+  vWithAppHeight=$(ffprobe -v error -select_streams v:0 -show_entries stream=height -of csv=s=x:p=0 $vWithApp)
+  echo "vWithAppWidth: $vWithAppWidth, vWithAppHeight: $vWithAppHeight"
+  #根据高度提供对话框尺寸与位置
+  if [ $vWithAppHeight -eq 1280 ]; then
+    dialogWidth=545
+    dialogHeight=334
+    startX=15
+    startY=180
+  else
+    echo "Unknown app video height"
+    return 1
+  fi
+  echo "dialogWidth: $dialogWidth, dialogHeight: $dialogHeight, startX: $startX, startY: $startY"
+  #根据对话框坐标，计算出对话框的区域
+  dialogArea="${dialogWidth}:${dialogHeight}:${startX}:${startY}"
+  echo "dialogArea: $dialogArea"
+  #根据对话框区域，抠出对话框
+  CMD="ffmpeg -i $vWithApp -filter:v \"crop=$dialogArea\" $vDialog"
+  echo $CMD
+  eval $CMD
+  if [ $? -ne 0 ]; then
+    echo "Failed to crop dialog from $vWithApp"
+    rm -f $vDialog
+    return 1
+  fi
+}
+
+function cropFinalVideos() {
+  appVideoDir="result/"
+  dialogVideoDir="result/dialog/"
+  for f in $appVideoDir*.mp4; do
+    #将f中的appVideoDir替换为dialogVideoDir
+    dialogVideoName=${f/$appVideoDir/$dialogVideoDir}
+    cropFinalVideo $f $dialogVideoName
+    if [ $? -ne 0 ]; then
+      echo "Failed to crop $f to $dialogVideoName"
+      exit 1
     fi
 
-done
+  done
+}
+
+#根据第一个参数选择功能：fake, cropFinalVideo
+if [ $1 == "fake" ]; then
+    # fake: 合成视频
+    # $2: 视频文件
+    # $3: 音频文件
+    ffmpeg -i $2 -i $3 -c:v copy -c:a aac -strict experimental -map 0:v:0 -map 1:a:0 -shortest output.mp4
+elif [ $1 == "crop" ]; then
+    cropFinalVideos
+else
+    echo "Unknown command"
+    exit 1
+fi
